// mutations
export const SETOWNEDTOKENS = 'SETOWNEDTOKENS'
export const SETIPFSDATA = 'SETIPFSDATA'

// actions
export const REGISTERTOKEN = 'REGISTERTOKEN'
export const FETCHOWNEDTOKENS = 'FETCHOWNEDTOKENS'
export const FETCHIPFSDATA = 'FETCHIPFSDATA'
export const TRANSFEROWNERSHIP = 'TRANSFEROWNERSHIP'
export const REMOVETOKEN = 'REMOVETOKEN'
