// mutations
export const ADDDOGADOPTIONS = 'ADDDOGADOPTIONS'
export const RESETDOGADOPTIONS = 'RESETDOGADOPTIONS'
export const DOGADOPTIONCANCELED = 'DOGADOPTIONCANCELED'
export const SETDOGADOPTION = 'SETDOGADOPTION'
export const ADDDOGADOPTERS = 'ADDDOGADOPTERS'
export const RESETDOGADOPTERS = 'RESETDOGADOPTERS'
export const SETWINNER = 'SETWINNER'
export const SETWITHDRAWAL = 'SETWITHDRAWAL'

// actions
export const CREATEDOGADOPTION = 'CREATEDOGADOPTION'
export const FETCHDOGADOPTIONS = 'FETCHDOGADOPTIONS'
export const FETCHDOGADOPTION = 'FETCHDOGADOPTION'
export const CANCELDOGADOPTION = 'CANCELDOGADOPTION'
export const ADOPT = 'ADOPT'
export const FETCHDOGADOPTERS = 'FETCHDOGADOPTERS'
export const MAKEWINNER = 'MAKEWINNER'
export const WITHDRAW = 'WITHDRAW'
