// mutations
export const FAILEDERROR = 'FAILEDERROR'
export const SETLOADING = 'SETLOADING'
export const SETADDRESS = 'SETADDRESS'
export const SETCURRENTACCOUNT = 'SETCURRENTACCOUNT'
export const SETNETWORKID = 'SETNETWORKID'
export const SETCURRENTBLOCK = 'SETCURRENTBLOCK'

// actions
export const ADDNETWORKADDRESS = 'ADDNETWORKADDRESS'
export const FETCHCURRENTACCOUNT = 'FETCHCURRENTACCOUNT'
export const FETCHCURRENTBLOCK = 'FETCHCURRENTBLOCK'
export const FAILED = 'FAILED'
