<template>
  <div>
    <v-dialog fullscreen v-model="dogAdoptDialog" transition="dialog-bottom-transition">
      <v-btn
        small
        class="text-capitalize mr-1 mb-1"
        outline
        slot="activator"
        :class="btnClass"
        :color="btnColor"
        :index="index"
        @click="openDialog"
      >Participate
        <v-icon right dark>pets</v-icon>
      </v-btn>
      <v-card>
        <v-toolbar dark color="indigo">
          <v-toolbar-title>Dog Adopter Registration</v-toolbar-title>
          <v-spacer></v-spacer>
          <v-btn icon @click="close" dark>
            <v-icon>close</v-icon>
          </v-btn>
        </v-toolbar>
        <v-divider></v-divider>
        <v-list v-if="!networkReady" subheader>
          <v-subheader style="color:red" class="mt-2">
            <v-icon color="red">error</v-icon>Error: Please make sure metamask is installed and connected to a network with an account selected
          </v-subheader>
        </v-list>
        <v-list v-else>
          <v-stepper v-model="stepperIndex" vertical>
            <v-stepper-step step="1" :complete="stepperIndex > 1">
              <span
                class="grey--text"
              >Create a Non-fungable token (ERC721 Complient) and upload dog owner info to IPFS (Interplanetary Files System)</span>
              <small>Create a token and upload dog owner info to IPFS</small>
            </v-stepper-step>
            <v-stepper-content step="1">
              <v-card>
                <v-form ref="assetForm">
                  <v-layout row wrap>
                    <v-flex>
                      <v-text-field
                        class="small"
                        maxlength="9"
                        prepend-icon="vpn_key"
                        color="indigo"
                        clearable
                        v-model="tokenId"
                        label="Token Id - Autogenerated(Edit if required)"
                        :rules="inputSpecificLengthRules"
                        required
                      ></v-text-field>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-text-field
                        prepend-icon="person"
                        color="indigo"
                        clearable
                        v-model="ipfs.name"
                        label="Owner Name"
                        :rules="inputMinRules"
                        required
                      ></v-text-field>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-text-field
                        prepend-icon="contact_phone"
                        color="indigo"
                        clearable
                        v-model="ipfs.phone"
                        label="Owner Phone"
                        :rules="inputMinRules"
                        required
                      ></v-text-field>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-textarea
                        prepend-icon="edit"
                        color="indigo"
                        clearable
                        v-model="ipfs.info"
                        label="Dog Info"
                        :rules="inputMinRules"
                        required
                      ></v-textarea>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-img v-if="ipfs.image" class="ml-4" :src="ipfs.image"></v-img>
                      <v-text-field
                        prepend-icon="attach_file"
                        color="indigo"
                        v-model="imageName"
                        label="Dog Picture"
                        :rules="[v => !!v || 'The field is required']"
                        required
                        @click="pickFile"
                      ></v-text-field>
                      <input
                        type="file"
                        style="display:none"
                        ref="image"
                        accept="image/*"
                        @change="onFilePicked"
                      >
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <div v-show="loading">
                        <span
                          class="caption black--text"
                        >Please wait while your asset is deployed and registered</span>
                        <v-progress-linear color="indigo" indeterminate></v-progress-linear>
                      </div>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-btn
                      class="mt-3"
                      outline
                      color="indigo"
                      @click="submitAsset"
                      flat
                      :loading="btnLoading"
                      :disabled="btnLoading"
                    >Create Token/Asset
                      <v-icon right dark>create</v-icon>
                    </v-btn>
                    <v-btn
                      class="mt-3"
                      outline
                      color="grey darken-2"
                      @click="skipAssets"
                      :disabled="this.btnLoading"
                      flat
                    >Skip
                      <v-icon right dark>skip_next</v-icon>
                    </v-btn>
                  </v-layout>
                </v-form>
              </v-card>
            </v-stepper-content>

            <v-stepper-step step="2" :complete="stepperIndex > 2">
              <span
                class="grey--text"
              >Transfer ownership of token to dog adoption repository or remove token</span>
              <small>Transfer ownership or remove</small>
            </v-stepper-step>
            <v-stepper-content step="2">
              <v-card>
                <v-form ref="transferOwnershipForm">
                  <v-layout row wrap>
                    <v-select
                      v-model="selectedToken"
                      prepend-icon="vpn_key"
                      :items="tokens"
                      label="Select a token"
                      style="max-width:180px"
                      :rules="[v => !!v || 'The field is required']"
                      @change="changeToken"
                    ></v-select>
                    <v-btn
                      outline
                      color="indigo"
                      flat
                      :loading="btnRemoveTokenLoading"
                      :disabled="btnRemoveTokenLoading"
                      @click="removeSelToken"
                      style="margin-top:12px"
                      class="ml-3"
                    >Remove Token
                      <v-icon right dark>remove</v-icon>
                    </v-btn>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <div v-show="loading">
                        <span class="caption black--text">{{ loadingMessage }}</span>
                        <v-progress-linear color="indigo" indeterminate></v-progress-linear>
                      </div>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-btn
                      class="mt-3"
                      outline
                      color="indigo"
                      @click="submitTransferOwnership"
                      flat
                      :loading="btnLoading"
                      :disabled="btnLoading"
                    >Transfer Ownership
                      <v-icon right dark>vpn_key</v-icon>
                    </v-btn>
                  </v-layout>
                </v-form>
              </v-card>
            </v-stepper-content>

            <v-stepper-step step="3" :complete="stepperIndex > 3">
              <span class="grey--text">Apply to dog adoption</span>
              <small>Apply</small>
            </v-stepper-step>
            <v-stepper-content step="3">
              <v-card>
                <v-form ref="paymentForum">
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-text-field
                        class="small"
                        maxlength="9"
                        prepend-icon="vpn_key"
                        color="indigo"
                        v-model="selectedToken"
                        label="Token Id (from previous step)"
                        :rules="inputSpecificLengthRules"
                        required
                        readonly
                      ></v-text-field>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-flex xs12 sm6 lg5>
                      <v-text-field
                        class="small"
                        color="indigo"
                        v-model="payment"
                        label="Ether"
                        placeholder="e.g. 0.1"
                        :rules="[v => /^\d*\.?\d*$/.test(v) || 'Must be decimal number']"
                      ></v-text-field>
                      <div v-show="loading">
                        <span class="caption black--text">Applying to dog adoption</span>
                        <v-progress-linear color="indigo" indeterminate></v-progress-linear>
                      </div>
                      <span class="caption">
                        You may send some wei to the dog adoption owner to support
                        the animal rescue organization but it is not required.
                      </span>
                    </v-flex>
                  </v-layout>
                  <v-layout row wrap>
                    <v-btn
                      class="mt-3"
                      outline
                      color="indigo"
                      @click="adoptDog"
                      flat
                      :loading="btnLoading"
                      :disabled="btnLoading"
                    >Apply
                      <v-icon right dark>pets</v-icon>
                    </v-btn>
                    <v-btn
                      class="mt-3"
                      outline
                      color="grey darken-2"
                      @click="close()"
                      flat
                      :disabled="btnLoading"
                    >Close
                      <v-icon right dark>close</v-icon>
                    </v-btn>
                  </v-layout>
                </v-form>
              </v-card>
            </v-stepper-content>
          </v-stepper>
        </v-list>
      </v-card>
      <v-snackbar
        v-model="snackbar"
        :multi-line="true"
        :left="true"
        :timeout="snackbarProp.timeout"
      >
        {{snackbarProp.content}}
        <v-btn color="indigo" flat @click="snackbar = false">Close</v-btn>
      </v-snackbar>
    </v-dialog>
    <v-dialog v-model="ipfsDataDialog" persistent width="700">
      <v-layout v-if="ipfsData" row wrap>
        <v-flex>
          <v-card flat>
            <v-img :src="ipfsData.image"></v-img>
            <v-card-title>
              <div>
                <h3 class="headline mb-0">
                  {{ ipfsData.name }}
                  <span class="subheading">({{ ipfsData.phone }})</span>
                </h3>
                <div class="grey--text">{{ ipfsData.info }}</div>
              </div>
            </v-card-title>
            <v-card-actions>
              <v-btn
                flat
                @click="ipfsDataDialog = false"
                color="indigo"
                outline
                class="text-capitalize ml-1"
              >Close</v-btn>
            </v-card-actions>
          </v-card>
        </v-flex>
      </v-layout>
    </v-dialog>
    <Dialog :dialog.sync="dialog">
      <template slot="title">{{dialogSlot.title}}</template>
      <template slot="content">{{dialogSlot.content}}</template>
    </Dialog>
  </div>
</template>

<script>
import { dogAdoptMixin } from "@/mixins/dogAdoptMixin";
import { ADOPT } from "@/store/dogAdoption/types";
import { mapActions } from "vuex";

export default {
  name: "DogAdopterDialog",
  mixins: [dogAdoptMixin],
  data() {
    return {
      payment: 0
    };
  },
  methods: {
    ...mapActions("dogAdoption", {
      adopt: ADOPT
    }),
    adoptDog() {
      if (this.$refs.paymentForum.validate()) {
        this.btnLoading = true;
        this.adopt({
          index: this.index,
          tokenId: this.selectedToken,
          value: this.payment
        }).then(() => {
          this.close();
          this.showSnackbar(
            `You are successfully added to the dog adoption as an adopter`
          );
          this.$router.push(`/adopters/${this.index}`);
        });
      }
    }
  }
};
</script>
